config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
  
  delete 'bookmarks/:id', to: 'bookmarks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.create(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "lists", class: "navbar-brand" do %>
      <%= image_tag "https://media.istockphoto.com/vectors/camera-movie-logo-vector-vector-id1276906195?s=612x612" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Lists", "lists", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New List", "lists/new", class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://movieposterhd.com/wp-content/uploads/2019/03/Game-of-Thrones-8-Season-Movies-Wallpaper-HD.jpg);">
  <div class="container">
    <h1>CineFreak is your newest movie companion!</h1>
    <p>Making movie listing & bookmarking as easy as ever.</p>
  </div>
</div>
<h1>My Lists<h1>

<div class="cards">
<% @lists.each do |list| %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= list.photo.attached? ? cl_image_path(list.photo.key) : asset_path('card_background.jpg') %>')">
  <h5><%= link_to list.name, list_path(list), class: 'link-font' %></h5>
  </div>
  <% end %>
</div>
 

app/views/lists/new.html.erb
<div class="col-12 col-md-6 offset-lg-3">
  <div class="bg-white rounded p-3 shadow">
    <h3>Create a new list</h3>
    <%= simple_form_for @list do |f| %>
      <%= f.input :name, placeholder: 'Action' %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="card-category card-large" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : asset_path('card_background.jpg') %>')">
  <h1><%= @list.name %></h1>
  <span class="movie-tag"><%= pluralize(@list.movies.size, 'movie') %></span>
</div>

<div class="d-flex justify-content-between my-4">
  <div>
    <%= link_to 'Add a movie', new_list_bookmark_path(@list) %>
      <%= link_to 'delete this list', list_path(@list), method: :delete, class: 'btn btn-cancel', data: { confirm: 'Are you sure you want to delete this list?' } %>
    <%= link_to 'Back to my lists', lists_path %>
  </div>
</div>

<div class="card-deck">
  <% @list.movies.each do |movie| %>
    <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
    <div class="card">
      <%= image_tag movie.poster_url, class: "card-img-top" %>
      <div class="card-body">
        <h5 class="card-title"><%= movie.title %></h5>
        <p class="card-text"><%= movie.overview %></p>
        <p class="card-text"><small class="text-muted"><%= movie.rating %></small></p>
        <p class="card-text"><small class="text-muted">"<%= bookmark.comment %>"</small></p>
      </div>
    </div>
    <% end %>
 </div>